name: "Securing our product"
on: pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.head.sha }}/merge
    - name: List all files
      run: ls -la $GITHUB_WORKSPACE
